# Generated by Django 3.2.3 on 2023-10-12 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscribe",
        ),
    ]
