# Generated by Django 3.2.3 on 2023-10-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_delete_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_name',
            new_name='measurement_unit',
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
    ]
