version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    depends_on:
      - db
    build: ../backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/backend_static/
      - media:/var/www/foodgram/media/
