version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: aihal21/foodgram_backend
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
    volumes:
      - static:/backend_static
      - media:/media/

  frontend:
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
    image: aihal21/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
    ports:
      - 6000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/backend_static/
      - media:/var/www/foodgram/media/