version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
      - DB_NAME=foodgram
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: aihal21/foodgram_backend
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
      - DB_NAME=foodgram
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - static:/backend_static
      - media:/media/

  frontend:
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
      - DB_NAME=foodgram
      - DB_HOST=db
      - DB_PORT=5432
    image: aihal21/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
      - DB_NAME=foodgram
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 6000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/backend_static/
      - media:/var/www/foodgram/media/