from enum import Enum


class ModelsConstants(Enum):
    NAME_LENGTH = 150
    PASSWORD_LENGTH = 150
    EMAIL_LENGTH = 254
    SLUG_LENGTH = 200
    TEXT_SMALL = 200
    COOCKING_TIME_MIN_VALUE = 1
    COOCKING_TIME_MAX_VALE = 1000
    INGREDIENT_MIN_AMOUNT = 1
    INGREDIENT_MAX_AMOUNT = 10000
