# Generated by Django 3.2.3 on 2023-10-12 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ingredient",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="author",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="recipe",
        ),
        migrations.AlterUniqueTogether(
            name="recipetag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="tag",
        ),
        migrations.AlterUniqueTogether(
            name="shoppingcart",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="subscribe",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="user_subscribed_on",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
        migrations.DeleteModel(
            name="RecipeTag",
        ),
        migrations.DeleteModel(
            name="ShoppingCart",
        ),
        migrations.DeleteModel(
            name="Subscribe",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
