# Generated by Django 3.2.3 on 2023-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
