# Generated by Django 3.2.3 on 2023-09-30 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('user_subscribed_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_subscribed_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
