# Generated by Django 3.2.3 on 2023-10-02 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_auto_20231002_1723"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["id"],
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["id"],
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ["id"],
                "verbose_name": "Recipe Ingredient",
                "verbose_name_plural": "Recipe's Ingredients",
            },
        ),
        migrations.AlterModelOptions(
            name="recipetag",
            options={
                "ordering": ["id"],
                "verbose_name": "Recipe Tag",
                "verbose_name_plural": "Recipe's Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="subscribe",
            options={
                "ordering": ["id"],
                "verbose_name": "Subscribe",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recepies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipe author",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Recipe name"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.CharField(
                max_length=200, verbose_name="Recipe description"
            ),
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_cart_recipes",
                        to="api.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_cart_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Carts",
                "ordering": ["id"],
            },
        ),
    ]
