# Generated by Django 3.2.3 on 2023-10-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231003_1523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_name')},
        ),
    ]
