# Generated by Django 3.2.3 on 2023-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_name',
            field=models.CharField(max_length=150, verbose_name='Unit of measure'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ingredient name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tag'),
        ),
    ]
